# Input
input:
  trait: "T2D_chr11"
  chr: "11"
  gwas_raw: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/GWAS_T2D_chr11.txt"
  gwas: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/GWAS_T2D_chr11.txt"
  output: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/results" 
script:
  work_path: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sbatch_test"
  path: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/scripts"
yaml:
  template: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/deploy/GAMMA.yaml"
  config: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/deploy/GAMMA.yaml"
# Not changed ---- :
environment:
  # R_421: "GAMMA_r"
  # python_pops: "GAMMA_pops"
  # python_depict: "GAMMA_depict"
  # python_rwr_ppr: "GAMMA_NetworkX"
  # python_ldsc: "GAMMA_ldsc"
  # post_smr: "GAMMA_depict"
  # python_ml: "GAMMA_ML"
  R_421:  "Drugsets_py385"
  python_pops: "pops"
  python_depict: "depict"
  python_rwr_ppr: "NetworkX"
  python_ldsc: "ldsc"
  post_smr: "depict"
  python_ml: "py39"
software:
  plink1_9: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/plink_1.90_beta"
  plink2: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/plink2"
  gcta: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/gcta-1.94.1"
  smr: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/smr-1.3.2-alpha7-linux"
  fusion: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/FUSION.assoc_test.R"
  coloc: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/COLOC.R"
  magma: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/magma"
  pops: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/pops.py"
  depict: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/depict.py"
  bedtools: "/storage/yangjianLab/guoyazhou/anaconda3/bin/bedtools"
  R_functions: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/CommonFunc.r"
  magic: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/softwares/magic_functions.r"
gene:
  gencode: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/gene/gencode.v40.GRCh38.gene.annotation.bed"
  gencode_tss: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/gene/gencode.v40.closestTSS.GRCh38.bed"
  gamma_gene: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/gene/GAMMA_gene_list.txt"
  gamma_gene_all: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/gene/GAMMA_gene_list_all_protein_coding.txt"
reference:
  reference_bfile: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/reference/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38"
  reference_bfile_GRCh37: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/reference/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K"
  reference_all_bim: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/reference/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38_chrALL.bim"
  reference_freq: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/reference/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38.frq"
clumping:
  field: "P"
magma:
  gene_annot: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/magma/genes_GRCh37.genes.annot"
mBAT:
  gene_list: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/mBATcombo/glist_ensgid_hg38_v40.txt"
v2g:
  Exon_bed: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/gene/gencode.v40.GRCh38.exon.bed"
  ABC_bed: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/e2g_file/ABC0.015_GRCh38_CHRALL.bed"
  EpiMap_bed: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/e2g_file/EpiMap_links_by_group.ALL.CHRALL_GRCh38.bed"
  RoadMap_bed: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/e2g_file/Roadmap_links_GRCh38.bed"
  PCHiC_bed: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/e2g_file/PCHiC_Combined_GRCh38.bed"
smr:
  maf: 0.01
  peqtl_smr: 5.0e-8
  peqtl_heidi: 1.57e-3
  batch_num: 1
  smr_multi_index: TRUE
  heidi_index: TRUE
  QTL_list: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/xQTL_file/user_xQTL_list.txt"
magic:
  run_magic_index: TRUE
  smr_multi_index: TRUE
  heidi_index: TRUE
  QTL_list: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/xQTL_file/user_xQTL_list.txt"
  QTL_name_list: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/xQTL_file/user_xQTL_name_list.txt"
  CpG_link: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/magic/CpG_consensus3.link"
  hQTL_link: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/magic/hQTL_consensus3.link"
  caQTL_link: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/magic/caQTL_consensus3.link"
coloc:
  QTL_dir: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/data/coloc"
  



l2g:
  L2G_column_file: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_github/gamma-script/scripts/L2G/L2G_column.r"
  QTL_name_mapping_file: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_git/L2G/QTL_data/L2G_QTL_name_mapping.txt"
  gsmr_pQTL_file: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_git_data/GSMR/data/gsmr_pQTL.txt"
  pQTL_epi_file: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sharedata/molecular_QTL/pQTL/freeze1/merged_pQTL_plasma/merged_pQTL_plasma_5pQTL.epi"

mr:
  enable: False
  batch_num: 10
  MR_snp_min: 3
  QTL_clumped_list: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_github/gamma-script/scripts/L2G/MR/QTL_clumped/QTL_clumped_list.txt"
  GSMR_QTL_clumped_list: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_github/gamma-script/scripts/L2G/MR/QTL_clumped/GSMR_QTL_clumped_list.txt"

fusion:
  munge_sumstats: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/software/LDSC/ldsc/munge_sumstats.py"
  ldsc_resources_dir: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sharedata/LDSC_resource"
  LDREF: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/software/FUSION/fusion_twas-master/LDREF"
  QTL_list: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_git/L2G/QTL_data/FUSION_QTL_name.txt"

gsmr:
  reffile: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_git_data/GSMR/data/gsmr_ref_data_ukb.txt"
  expofile: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_git_data/GSMR/data/gsmr_pQTL.txt"
  expo_dir: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_git_data/GSMR/exposure_data"
pops:
  gene_annot: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/software/PoPS/pops-master/example/data/utils/gene_annot_jun10.txt"
  pops_feature: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/software/PoPS/pops-master/pops_all_features_munged/all_pops_features"
  control_feature: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/software/PoPS/pops-master/example/data/utils/features_jul17_control.txt"
depict:
  snp_loc_GRCh37: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/software/DEPICT/snp_loc_b37"
  cfg_demo: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_git_data/DEPICT/cfg/demo.cfg"
rwr_ppr:
  ppi_file: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sharedata/Network_data/PPI/PPI_all.csv"
gamma:
  pharmaprojects: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/github/Network/data/clinical_targets/target_indication/Pharmaprojects_2024_05_07.txt"
  pharmaprojects_nelson: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_git/clinical_success_rate/Pharmaprojects_Nelson_2022.txt"
  pharmaprojects_0507_shufeng: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sunshufeng/gamma_v4/data/pharmap_processed.csv"
mesh:
  gwas_mesh: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/guoyazhou/GAMMA_git/GWAS_trait_list/trait_mapping_latest.txt"
# Model
model_data:
  omim: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sunshufeng/gamma_v4/data/OMIM_processed.csv"
  clinvar: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sunshufeng/gamma_v4/data/clinvar.csv"
  mgi: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sunshufeng/gamma_v4/data/MGI_processed.csv"
  gene_features: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sunshufeng/gamma_v4/0.0.3_gene_features.csv"
model_model:
  model: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sunshufeng/gamma_v4/0.0.1_valid_feature_model.joblib"
  feature: "/storage/yangjianLab/guoyazhou/github/GAMMA_for_PC_testing/sunshufeng/gamma_v4/0.0.2_feature_list.txt"
