#Adjust the input before running the code.
#Adjust QTL_list files for a different set of QTLs.
input:
  GAMMA_HOME: "/home/sunshufeng/GAMMA_for_PC_testing"
  trait: "T2D_chr11"
  chr: "11"
  mesh_id: "D003924"
  gwas_raw: "${GAMMA_HOME}/data/GWAS_T2D_chr11.txt"
  gwas: "${GAMMA_HOME}/data/GWAS_T2D_chr11.txt"
  output: "${GAMMA_HOME}/results" 
script:
  path: "${GAMMA_HOME}/scripts"
yaml:
  template: "${GAMMA_HOME}/deploy/GAMMA.yaml"
  config: "${GAMMA_HOME}/deploy/GAMMA.yaml"
environment:
  R_421: "GAMMA_r"
  python_pops: "GAMMA_pops"
  python_depict: "GAMMA_depict"
  python_rwr_ppr: "GAMMA_NetworkX"
  python_ldsc: "GAMMA_ldsc"
  post_smr: "GAMMA_depict"
  python_ml: "GAMMA_ML"
software:
  plink1_9: "${GAMMA_HOME}/softwares/plink_1.90_beta"
  plink2: "${GAMMA_HOME}/softwares/plink2"
  gcta: "${GAMMA_HOME}/softwares/gcta-1.94.1"
  smr: "${GAMMA_HOME}/softwares/smr-1.3.2-alpha7-linux"
  smr_lib: "${GAMMA_HOME}/softwares/libstdcxx-ng-12.2.0/lib"
  fusion: "${GAMMA_HOME}/softwares/FUSION.assoc_test.R"
  coloc: "${GAMMA_HOME}/softwares/COLOC.R"
  magma: "${GAMMA_HOME}/softwares/magma"
  pops: "${GAMMA_HOME}/softwares/pops.py"
  depict: "${GAMMA_HOME}/data/depict/src/python/depict.py"
  # bedtools: "/storage/yangjianLab/guoyazhou/anaconda3/bin/bedtools" ### conda activate GAMMA_depict
  R_functions: "${GAMMA_HOME}/softwares/CommonFunc.r"
  magic: "${GAMMA_HOME}/softwares/magic_functions.r"
gene:
  gencode: "${GAMMA_HOME}/data/gene/gencode.v40.GRCh38.gene.annotation.bed"
  gencode_tss: "${GAMMA_HOME}/data/gene/gencode.v40.closestTSS.GRCh38.bed"
  gamma_gene: "${GAMMA_HOME}/data/gene/GAMMA_gene_list.txt"
  gamma_gene_all: "${GAMMA_HOME}/data/gene/GAMMA_gene_list_all_protein_coding.txt"
reference:
  reference_bfile: "${GAMMA_HOME}/data/reference/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38"
  reference_bfile_GRCh37: "${GAMMA_HOME}/data/reference/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K"
  reference_all_bim: "${GAMMA_HOME}/data/reference/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38_chrALL.bim"
  reference_freq: "${GAMMA_HOME}/data/reference/BED_ukbEUR_imp_v3_INFO0.8_maf0.01_mind0.05_geno0.05_hwe1e6_10K_hg38.frq"
clumping:
  field: "P"
magma:
  gene_annot: "${GAMMA_HOME}/data/magma/genes_GRCh37.genes.annot"
mBAT:
  gene_list: "${GAMMA_HOME}/data/mBATcombo/glist_ensgid_hg38_v40.txt"
v2g:
  Exon_bed: "${GAMMA_HOME}/data/gene/gencode.v40.GRCh38.exon.bed"
  ABC_bed: "${GAMMA_HOME}/data/e2g_file/ABC0.015_GRCh38_CHRALL.bed"
  EpiMap_bed: "${GAMMA_HOME}/data/e2g_file/EpiMap_links_by_group.ALL.CHRALL_GRCh38.bed"
  RoadMap_bed: "${GAMMA_HOME}/data/e2g_file/Roadmap_links_GRCh38.bed"
  PCHiC_bed: "${GAMMA_HOME}/data/e2g_file/PCHiC_Combined_GRCh38.bed"
smr:
  maf: 0.01
  peqtl_smr: 5.0e-8
  peqtl_heidi: 1.57e-3
  batch_num: 1
  smr_multi_index: TRUE
  heidi_index: TRUE
  QTL_list: "${GAMMA_HOME}/data/xQTL_file/user_xQTL_list.txt"
magic:
  run_magic_index: TRUE
  smr_multi_index: TRUE
  heidi_index: TRUE
  QTL_list: "${GAMMA_HOME}/data/xQTL_file/user_xQTL_list.txt"
  QTL_name_list: "${GAMMA_HOME}/data/xQTL_file/user_xQTL_name_list.txt"
  CpG_link: "${GAMMA_HOME}/data/magic/CpG_consensus3.link"
  hQTL_link: "${GAMMA_HOME}/data/magic/hQTL_consensus3.link"
  caQTL_link: "${GAMMA_HOME}/data/magic/caQTL_consensus3.link"
coloc:
  QTL_dir: "${GAMMA_HOME}/data/coloc"
fusion:
  munge_sumstats: "${GAMMA_HOME}/data/fusion/munge_sumstats.py"
  ldsc_resources_dir: "${GAMMA_HOME}/data/fusion/LDSC_resource"
  LDREF: "${GAMMA_HOME}/data/fusion/LDREF"
  QTL_list: "${GAMMA_HOME}/data/fusion/FUSION_QTL_name.txt"
mr:
  enable: False
  batch_num: 10
  MR_snp_min: 3
  GSMR_QTL_clumped_list: "${GAMMA_HOME}/data/mr/GSMR_QTL_clumped_list.txt"
l2g:
  L2G_column_file: "${GAMMA_HOME}/data/l2g/L2G_column.r"
  QTL_name_mapping_file: "${GAMMA_HOME}/data/l2g/L2G_QTL_name_mapping.txt"
  gsmr_pQTL_file: "${GAMMA_HOME}/data/l2g/gsmr_pQTL.txt"
  pQTL_epi_file: "${GAMMA_HOME}/data/l2g/merged_pQTL_plasma_5pQTL.epi"
pops:
  gene_annot: "${GAMMA_HOME}/data/pops/gene_annot_jun10.txt"
  pops_feature: "${GAMMA_HOME}/data/pops/pops_all_features_munged/all_pops_features"
  control_feature: "${GAMMA_HOME}/data/pops/features_jul17_control.txt"
depict:
  snp_loc_GRCh37: "${GAMMA_HOME}/data/depict/snp_loc_b37_chr11.txt"
  cfg_demo: "${GAMMA_HOME}/data/depict/demo.cfg"
rwr_ppr:
  ppi_file: "${GAMMA_HOME}/data/rwr_ppr/PPI_all.csv"
gamma:
  pharmaprojects: "${GAMMA_HOME}/data/gamma/Pharmaprojects_2024_05_07.txt"
  pharmaprojects_nelson: "${GAMMA_HOME}/data/gamma/Pharmaprojects_Nelson_2022.txt"
  pharmaprojects_0507_shufeng: "${GAMMA_HOME}/data/gamma/pharmap_processed.csv"
mesh:
  gwas_mesh: "${GAMMA_HOME}/data/gamma/trait_mapping_latest.txt"
model_data:
  omim: "${GAMMA_HOME}/data/machine_learning/OMIM_processed.csv"
  clinvar: "${GAMMA_HOME}/data/machine_learning/clinvar.csv"
  mgi: "${GAMMA_HOME}/data/machine_learning/MGI_processed2.csv"
  gene_features: "${GAMMA_HOME}/data/machine_learning/0.0.3_gene_features.csv"
  uniprot: "${GAMMA_HOME}/data/machine_learning/0.0.5_uniprot_protein_family.csv"
model_model:
  model: "${GAMMA_HOME}/data/machine_learning/0.0.1_model.pth"
  scaler: "${GAMMA_HOME}/data/machine_learning/0.0.2_scaler.pkl"
